const projects = [
  {
    id: 1, name: '제주대학교 미래교육관 신축공사', noticeNo: 'R26BK01018432', address: '제주특별자치도 제주시 제주대학로 102', stage: '공고중', stageCls: 'open', usage: '교육시설', constructionType: '신축', area: 7906, cost: 205, unit: 261, deadline: '2026-08-27', dday: 'D-6', openDate: '2026-08-28', org: '제주대학교', region: '제주', trade: '건축공사업', method: '일반경쟁', awardMethod: '적격심사', conditionTags: ['제주', '실적', '공동도급'], regionLimited: true, performance: true, joint: true, pq: false, correction: false, rebid: false,
    badges: ['설계공모', '내역서', '제로에너지', '창호일람표'], opp: 87, fit: 92, actual: 37, ai: 6, next: '입찰 검토', nextSub: '설계사·참여 시공사 검토 가능', nextTarget: '설계사', awarded: '', awardPrice: '', awardRate: '', procurement: '혼합', demand: '철근·레미콘·창호 외', attachments: ['공사내역서', '시방서', '설계도서', '창호일람표'], hasContest: true, hasMap: true, awardAge: null, beforeStart: false,
    timeline: [['사업기획','24.08','done'],['설계공모','25.02','done'],['설계사 선정','25.05','done'],['실시설계','26.06','done'],['시공입찰','26.08','current'],['낙찰','26.09 예상','future'],['착공','26.10 예상','future'],['준공','28.03 예상','future']],
    designer: {name:'아틀리에 제주건축사사무소', similar:8, avg:'183억', fields:'교육시설 · 문화시설 · 공공건축'},
    issuer: {name:'제주대학교', count:18, total:'2,410억', avg:'134억', pattern:['교육시설 발주 증가','100~300억 사업 비중 높음','설계공모 활용률 높음']},
    materials: [
      {category:'철근콘크리트', name:'철근 SD400', spec:'HD10·13·16·19', unit:'ton', qty:69.33, source:'공사내역서', procurement:'사급', quantityType:'제품수량'},
      {category:'철근콘크리트', name:'레미콘', spec:'25-30-150 외 3종', unit:'㎥', qty:770, source:'공사내역서', procurement:'사급', quantityType:'제품수량'},
      {category:'철골', name:'H형강 SS275', spec:'5개 규격', unit:'ton', qty:29.01, source:'공사내역서', procurement:'사급', quantityType:'제품수량'},
      {category:'외장', name:'그라스울패널', spec:'T75 · 준불연', unit:'㎡', qty:520, source:'시방서', procurement:'사급', quantityType:'제품수량'},
      {category:'창호', name:'시스템창호', spec:'단열바 적용', unit:'㎡', qty:610, source:'창호일람표', procurement:'사급', quantityType:'제품수량'}
    ],
    packages: [
      {name:'철근·콘크리트 패키지', type:'제품·자재 납품', score:91, target:'낙찰 시공사', timing:'낙찰 직후', substitute:'높음', items:['철근 SD400 69.33ton','레미콘 770㎥','H형강 SS275 29.01ton']},
      {name:'외피·창호 패키지', type:'공급+시공', score:84, target:'설계사 → 시공사', timing:'지금~낙찰 직후', substitute:'중간', items:['그라스울패널 T75 520㎡','시스템창호 610㎡']}
    ],
    specs: [{label:'제로에너지', type:'official'},{label:'준불연', type:'official'},{label:'고성능 외피', type:'ai'},{label:'동등이상 허용', type:'official'}],
    aiMaterials: [{name:'고성능 로이유리', score:86, reason:'설계공모 당선안·창호일람표·유사 교육시설 분석', target:'설계사', timing:'현재~3개월', official:false},{name:'흡음재',score:78,reason:'교육·커뮤니티 공간 비중',target:'설계사',timing:'현재',official:false},{name:'외장패널',score:71,reason:'당선안 외관 및 외피면적 분석',target:'시공사',timing:'낙찰 이후',official:false}],
    costSheet: [{name:'직접재료비',amount:'71.2억',ratio:'35.9%'},{name:'간접재료비',amount:'10.9억',ratio:'5.5%'},{name:'직접노무비',amount:'39.7억',ratio:'20.0%'},{name:'간접노무비',amount:'7.1억',ratio:'3.6%'},{name:'기계경비',amount:'12.4억',ratio:'6.3%'},{name:'안전관리비',amount:'4.1억',ratio:'2.1%'},{name:'일반관리비',amount:'8.6억',ratio:'4.3%'},{name:'이윤',amount:'12.5억',ratio:'6.3%'}],
    files: [{name:'공사입찰공고서.pdf',meta:'PDF · 2.4MB',type:'공고문'},{name:'공사내역서.xlsx',meta:'XLSX · 4.8MB',type:'공사내역서'},{name:'건축공사 시방서.pdf',meta:'PDF · 15.2MB',type:'시방서'},{name:'창호일람표.pdf',meta:'PDF · 6.2MB',type:'일람표'},{name:'설계도서.zip',meta:'ZIP · 128MB',type:'설계도서'}],
    aiSummary:'기존 교육시설을 대체하고 미래교육 환경을 구축하기 위한 약 7,900㎡ 규모의 공공 교육시설 신축사업입니다. 설계공모와 실시설계가 완료되어 현재 시공입찰 단계이며, 창호·외장·단열·흡음 및 고효율 설비 관련 납품기회를 검토할 가치가 높습니다.'
  },
  {
    id: 2, name: '대구 공영주차장 조성공사', noticeNo: 'R26BK00972812', address: '대구광역시 달서구 월배로 31', stage: '낙찰완료', stageCls: 'award', usage: '자동차관련시설', constructionType:'신축', area: 13255, cost: 74, unit: 188, deadline: '2026-08-05', dday: '낙찰', openDate:'2026-08-05', org: '대구광역시', region: '대구', trade:'토목공사업', method:'제한경쟁', awardMethod:'적격심사', conditionTags:['대구','실적'], regionLimited:true, performance:true, joint:false, pq:false, correction:false, rebid:false,
    badges:['물량','낙찰','AI 분석','특정모델'], opp:90, fit:74, actual:42, ai:8, next:'시공사 영업', nextSub:'낙찰 후 9일', nextTarget:'시공사', awarded:'대구종합건설', awardPrice:'67.8억', awardRate:'91.6%', procurement:'혼합', demand:'가로등·주차블록·아스콘 외', attachments:['공사내역서','물량내역서','시방서'], hasContest:false, hasMap:true, awardAge:9, beforeStart:true,
    timeline:[['사업기획','25.11','done'],['설계','26.02','done'],['입찰','26.07','done'],['낙찰','26.08','current'],['계약','26.08 예상','future'],['착공','26.09 예상','future'],['준공','27.04 예상','future']],
    designer:{name:'대구도시기술단',similar:5,avg:'78억',fields:'주차장 · 도로 · 토목'}, issuer:{name:'대구광역시',count:32,total:'4,820억',avg:'151억',pattern:['주차·교통시설 발주 지속','사급자재 비중 높은 토목공사','낙찰 후 착공 간격 짧음']},
    materials:[
      {category:'주차시설',name:'PE주차블록',spec:'750×150×120mm',unit:'EA',qty:792,source:'공사내역서',procurement:'사급',quantityType:'제품수량'},
      {category:'조명',name:'태양광가로등',spec:'DMTPS-310 · 50W · 5m',unit:'본',qty:20,source:'공사내역서',procurement:'관급',quantityType:'계약수량'},
      {category:'포장',name:'아스콘 표층',spec:'WC-2 · 가열3등급',unit:'ton',qty:2152,source:'공사내역서',procurement:'사급',quantityType:'제품수량'},
      {category:'배수',name:'PE이중벽하수관',spec:'Φ400',unit:'m',qty:27,source:'공사내역서',procurement:'사급',quantityType:'제품수량'},
      {category:'배수',name:'무소음그레이팅',spec:'500×1000×50',unit:'조',qty:24,source:'공사내역서',procurement:'관급',quantityType:'계약수량'},
      {category:'조경',name:'남천·영산홍',spec:'H0.8 / H0.3',unit:'주',qty:4772,source:'물량내역서',procurement:'사급',quantityType:'제품수량'}
    ],
    packages:[
      {name:'태양광 가로등 패키지',type:'장비·기계 납품',score:94,target:'조달 담당·시공사',timing:'지금',substitute:'제한적',items:['태양광가로등 20본','가로등기초 20EA','앵커볼트 80개','베이스커버 20개']},
      {name:'주차시설 패키지',type:'제품·자재 납품',score:92,target:'낙찰 시공사',timing:'지금',substitute:'높음',items:['PE주차블록 792개','주차라인 관련 시공']},
      {name:'도로포장 패키지',type:'공급+시공',score:88,target:'전문건설사',timing:'착공 전',substitute:'중간',items:['아스콘 2,152ton','포설·다짐 13,255㎡','디스트리뷰터 3,800ℓ급']},
      {name:'배수시설 패키지',type:'공급+시공',score:81,target:'전문건설사',timing:'착공 전',substitute:'높음',items:['PE이중벽하수관 Φ400 27m','PE밴드 3조','무소음그레이팅 24조']}
    ],
    specs:[{label:'태양광',type:'official'},{label:'특정모델',type:'official'},{label:'대체가능성 확인 필요',type:'ai'}],
    aiMaterials:[{name:'고효율 조명제어',score:82,reason:'태양광가로등 20본 및 주차장 운영 특성',target:'시공사',timing:'지금',official:false},{name:'주차유도 설비',score:76,reason:'792면 규모 주차시설 수요 분석',target:'시공사',timing:'낙찰 직후',official:false}],
    costSheet:[{name:'재료비',amount:'31.6억',ratio:'46.6%'},{name:'노무비',amount:'12.4억',ratio:'18.3%'},{name:'경비',amount:'9.8억',ratio:'14.5%'},{name:'일반관리·이윤',amount:'7.2억',ratio:'10.6%'}],
    files:[{name:'공사내역서.xlsx',meta:'XLSX · 3.7MB',type:'공사내역서'},{name:'물량내역서.xlsx',meta:'XLSX · 1.8MB',type:'물량내역서'},{name:'특기시방서.pdf',meta:'PDF · 8.1MB',type:'시방서'}],
    aiSummary:'주차장 조성과 도로포장·배수·조명·조경을 포함한 복합 토목공사입니다. 낙찰자가 확정된 직후 단계로, 사급 주차시설·포장재와 일부 관급 조명·배수 제품의 납품 담당자를 구분해 접근하는 것이 중요합니다.'
  },
  {
    id:3,name:'부산 공공도서관 신축공사',noticeNo:'R26BK00811881',address:'부산광역시 해운대구 센텀로 88',stage:'착공예정',stageCls:'soon',usage:'문화시설',constructionType:'신축',area:10790,cost:312,unit:289,deadline:'2026-07-29',dday:'착공 D-22',openDate:'2026-07-30',org:'부산광역시',region:'부산',trade:'건축공사업',method:'일반경쟁',awardMethod:'종합심사',conditionTags:['부산','실적','PQ'],regionLimited:false,performance:true,joint:true,pq:true,correction:true,rebid:false,
    badges:['당선안','원가','낙찰','창호일람표'],opp:93,fit:88,actual:48,ai:9,next:'자재 영업',nextSub:'착공 D-22',nextTarget:'시공사',awarded:'부산건설',awardPrice:'287억',awardRate:'92.0%',procurement:'혼합',demand:'창호·단열·외장 외',attachments:['공사내역서','시방서','마감재료표','창호일람표'],hasContest:true,hasMap:true,awardAge:22,beforeStart:true,
    timeline:[['설계공모','24.09','done'],['설계사 선정','24.12','done'],['실시설계','25.11','done'],['입찰','26.07','done'],['낙찰','26.07','done'],['계약','26.08','current'],['착공','26.09 예상','future'],['준공','28.01 예상','future']],
    designer:{name:'도시공간건축사사무소',similar:12,avg:'240억',fields:'도서관 · 문화시설 · 공공건축'},issuer:{name:'부산광역시',count:41,total:'8,120억',avg:'198억',pattern:['문화시설 발주 증가','대형 공공건축 비중 높음','친환경·고성능 외피 요구 증가']},
    materials:[{category:'창호',name:'시스템창호',spec:'단열바 적용',unit:'㎡',qty:860,source:'창호일람표',procurement:'사급',quantityType:'제품수량'},{category:'창호',name:'복층유리',spec:'24mm',unit:'㎡',qty:1240,source:'창호일람표',procurement:'사급',quantityType:'제품수량'},{category:'내장',name:'흡음패널',spec:'T25',unit:'㎡',qty:690,source:'마감재료표',procurement:'사급',quantityType:'제품수량'},{category:'외장',name:'외장패널',spec:'준불연',unit:'㎡',qty:1830,source:'마감재료표',procurement:'사급',quantityType:'제품수량'}],
    packages:[{name:'창호·유리 패키지',type:'공급+시공',score:96,target:'낙찰 시공사',timing:'지금',substitute:'높음',items:['시스템창호 860㎡','복층유리 1,240㎡','방화창 별도 사양']},{name:'외장·흡음 마감 패키지',type:'공급+시공',score:89,target:'시공사·전문건설사',timing:'착공 전',substitute:'중간',items:['외장패널 1,830㎡','흡음패널 690㎡']}],
    specs:[{label:'준불연',type:'official'},{label:'고단열',type:'official'},{label:'방화창',type:'official'},{label:'친환경 흡음',type:'ai'}],aiMaterials:[{name:'로이복층유리 고성능 대안',score:91,reason:'창호일람표·에너지 요구 분석',target:'시공사',timing:'지금',official:false},{name:'친환경 흡음재',score:84,reason:'도서관 실내환경 요구',target:'전문건설사',timing:'착공 전',official:false}],costSheet:[{name:'재료비',amount:'126.4억',ratio:'44.0%'},{name:'노무비',amount:'61.2억',ratio:'21.3%'},{name:'경비',amount:'47.1억',ratio:'16.4%'},{name:'관리·이윤',amount:'31.2억',ratio:'10.9%'}],files:[{name:'창호일람표.pdf',meta:'PDF · 6.2MB',type:'일람표'},{name:'마감재료표.xlsx',meta:'XLSX · 2.2MB',type:'일람표'},{name:'공사원가계산서.xlsx',meta:'XLSX · 1.1MB',type:'원가계산서'},{name:'특기시방서.pdf',meta:'PDF · 11.9MB',type:'시방서'}],aiSummary:'공공도서관 신축공사로 낙찰과 계약이 완료되어 착공을 앞둔 단계입니다. 창호일람표와 마감재료표가 확보되어 실제 시스템창호·유리·외장·흡음 수요를 확인할 수 있으며, 지금은 시공사 구매·VE 담당자에게 접근하기 좋은 시점입니다.'
  },
  {
    id:4,name:'광주 어린이복합문화시설 건립사업',noticeNo:'사전프로젝트-2026-014',address:'광주광역시 북구 문화길 15',stage:'설계완료',stageCls:'design',usage:'문화시설',constructionType:'신축',area:6160,cost:149,unit:242,deadline:'입찰예정',dday:'예정',openDate:'',org:'광주광역시',region:'광주',trade:'입찰공고 전',method:'미정',awardMethod:'미정',conditionTags:['입찰 전'],regionLimited:false,performance:false,joint:false,pq:false,correction:false,rebid:false,
    badges:['설계공모','당선안','AI 분석'],opp:86,fit:68,actual:0,ai:7,next:'설계사 영업',nextSub:'사양 반영 가능 시점',nextTarget:'설계사',awarded:'',awardPrice:'',awardRate:'',procurement:'확인불가',demand:'공식 물량 미확인',attachments:['설계공모','당선안','실시설계 요약'],hasContest:true,hasMap:true,awardAge:null,beforeStart:false,
    timeline:[['사업기획','24.11','done'],['설계공모','25.04','done'],['설계사 선정','25.07','done'],['실시설계','26.08','current'],['시공입찰','26.10 예상','future'],['착공','27.01 예상','future']],designer:{name:'공간이음 건축사사무소',similar:9,avg:'156억',fields:'어린이시설 · 문화시설 · 공공건축'},issuer:{name:'광주광역시',count:26,total:'3,340억',avg:'128억',pattern:['어린이·문화시설 발주 증가','친환경 마감 선호','설계단계 제품사양 협의 가능성 높음']},materials:[],packages:[],specs:[{label:'흡음성능',type:'ai'},{label:'친환경 마감',type:'ai'}],aiMaterials:[{name:'시스템창호',score:82,reason:'대형 문화시설 외피·당선안 분석',target:'설계사',timing:'지금',official:false},{name:'흡음재',score:79,reason:'어린이·문화공간 분석',target:'설계사',timing:'지금',official:false},{name:'친환경 마감재',score:77,reason:'공공 어린이시설 기준 분석',target:'설계사',timing:'지금',official:false}],costSheet:[],files:[{name:'당선안.pdf',meta:'PDF · 21MB',type:'설계공모'},{name:'설계설명서.pdf',meta:'PDF · 12MB',type:'설계도서'}],aiSummary:'입찰공고 전 실시설계 단계의 어린이 복합문화시설입니다. 아직 공식 공사내역서가 없어 실제 자재 수량은 표시하지 않으며, 당선안·설계설명서와 유사 프로젝트를 기반으로 창호·흡음·친환경 마감재의 설계사 영업기회만 별도 AI 추론으로 제공합니다.'
  },
  {
    id:5,name:'세종 스마트업무센터 리모델링공사',noticeNo:'R26BK01044190',address:'세종특별자치시 한누리대로 2150',stage:'공고중',stageCls:'open',usage:'업무시설',constructionType:'리모델링',area:12400,cost:168,unit:135,deadline:'2026-08-24',dday:'D-3',openDate:'2026-08-25',org:'행정중심복합도시건설청',region:'세종',trade:'건축공사업',method:'제한경쟁',awardMethod:'적격심사',conditionTags:['실적','공동도급'],regionLimited:false,performance:true,joint:true,pq:false,correction:false,rebid:true,
    badges:['재공고','내역서','BEMS','고효율'],opp:89,fit:85,actual:33,ai:8,next:'입찰 검토',nextSub:'마감 D-3 · 설비업체 선제 견적 가능',nextTarget:'시공사',awarded:'',awardPrice:'',awardRate:'',procurement:'혼합',demand:'공조기·BEMS·LED·창호 외',attachments:['공사내역서','기계장비일람표','전기부하표','특기시방서'],hasContest:false,hasMap:true,awardAge:null,beforeStart:false,
    timeline:[['기본계획','25.09','done'],['설계','26.03','done'],['시공입찰','26.08','current'],['낙찰','26.09 예상','future'],['착공','26.10 예상','future']],designer:{name:'에너지플랜 건축사사무소',similar:14,avg:'172억',fields:'업무시설 · 리모델링 · 에너지'},issuer:{name:'행정중심복합도시건설청',count:34,total:'7,620억',avg:'224억',pattern:['리모델링 발주 증가','고효율 설비 적용률 높음','BEMS·에너지성능 요구 빈번']},materials:[{category:'기계설비',name:'공조기',spec:'20,000CMH급',unit:'대',qty:8,source:'기계장비일람표',procurement:'사급',quantityType:'제품수량'},{category:'자동제어',name:'BEMS 제어패널',spec:'BACnet 연동',unit:'식',qty:1,source:'특기시방서',procurement:'사급',quantityType:'계약수량'},{category:'전기',name:'LED 조명기구',spec:'고효율 인증',unit:'EA',qty:1260,source:'전기부하표',procurement:'관급',quantityType:'계약수량'},{category:'창호',name:'로이복층유리',spec:'24mm',unit:'㎡',qty:940,source:'공사내역서',procurement:'사급',quantityType:'제품수량'}],packages:[{name:'BEMS·자동제어 패키지',type:'장비·기계 납품',score:95,target:'설계사·입찰 시공사',timing:'지금',substitute:'중간',items:['BEMS 제어패널 1식','BACnet 연동','센서·계측기 포함']},{name:'공조설비 패키지',type:'공급+시공',score:92,target:'입찰 시공사',timing:'지금~낙찰 직후',substitute:'높음',items:['공조기 8대','덕트·제어 연계']},{name:'고효율 조명 패키지',type:'제품·자재 납품',score:76,target:'조달 담당',timing:'낙찰 후',substitute:'제한적',items:['LED 조명 1,260EA · 고효율 인증']}],specs:[{label:'BEMS',type:'official'},{label:'BACnet',type:'official'},{label:'고효율 인증',type:'official'},{label:'저탄소 리모델링',type:'ai'}],aiMaterials:[{name:'고성능 창호 프레임',score:88,reason:'로이복층유리 940㎡ 및 에너지 리모델링 요구',target:'설계사',timing:'지금',official:false},{name:'실내공기질 센서',score:83,reason:'BEMS·공조기 패키지 연동 가능',target:'설계사',timing:'지금',official:false}],costSheet:[{name:'재료비',amount:'78.9억',ratio:'47.0%'},{name:'노무비',amount:'34.2억',ratio:'20.4%'},{name:'경비',amount:'21.5억',ratio:'12.8%'},{name:'관리·이윤',amount:'17.8억',ratio:'10.6%'}],files:[{name:'공사내역서.xlsx',meta:'XLSX · 5.1MB',type:'공사내역서'},{name:'기계장비일람표.xlsx',meta:'XLSX · 1.9MB',type:'일람표'},{name:'전기부하표.xlsx',meta:'XLSX · 1.2MB',type:'일람표'},{name:'특기시방서.pdf',meta:'PDF · 16MB',type:'시방서'}],aiSummary:'업무시설 에너지 리모델링 공사로 BEMS·자동제어·공조·고효율 조명이 핵심입니다. 기계장비일람표와 전기부하표가 확보되어 실제 장비 대수와 인증 요구를 확인할 수 있고, 마감이 임박해 입찰 시공사에 선제 견적을 제공하기 좋은 프로젝트입니다.'
  },
  {
    id:6,name:'경기 북부 공공의료원 증축공사',noticeNo:'R26BK00999341',address:'경기도 의정부시 의료원로 65',stage:'계약',stageCls:'award',usage:'의료시설',constructionType:'증축',area:18400,cost:486,unit:264,deadline:'2026-07-18',dday:'계약',openDate:'2026-07-19',org:'경기도의료원',region:'경기',trade:'건축공사업',method:'일반경쟁',awardMethod:'종합심사',conditionTags:['실적','PQ','공동도급'],regionLimited:false,performance:true,joint:true,pq:true,correction:false,rebid:false,
    badges:['낙찰','의료','특수설비','내역서'],opp:95,fit:81,actual:56,ai:11,next:'전문건설사 영업',nextSub:'계약 완료 · 전문공종 선정 예상',nextTarget:'전문건설사',awarded:'한빛건설',awardPrice:'448억',awardRate:'92.2%',procurement:'혼합',demand:'의료가스·공조·방화·위생 외',attachments:['공사내역서','기계장비일람표','의료가스시방서','방화구획도'],hasContest:false,hasMap:true,awardAge:29,beforeStart:true,
    timeline:[['설계','25.04','done'],['입찰','26.06','done'],['낙찰','26.07','done'],['계약','26.08','current'],['착공','26.09 예상','future'],['준공','29.02 예상','future']],designer:{name:'메디컬스페이스건축',similar:18,avg:'420억',fields:'병원 · 의료시설 · 연구시설'},issuer:{name:'경기도의료원',count:14,total:'5,930억',avg:'424억',pattern:['의료시설 증축·리모델링 지속','특수설비 비중 높음','전문공종 선정기간 길음']},materials:[{category:'기계설비',name:'의료가스 배관',spec:'동관 K-Type',unit:'m',qty:4860,source:'의료가스시방서',procurement:'사급',quantityType:'제품수량'},{category:'기계설비',name:'AHU',spec:'HEPA 대응',unit:'대',qty:14,source:'기계장비일람표',procurement:'사급',quantityType:'제품수량'},{category:'방화',name:'방화문',spec:'60분',unit:'EA',qty:148,source:'공사내역서',procurement:'사급',quantityType:'제품수량'},{category:'위생',name:'위생기구',spec:'의료시설형',unit:'SET',qty:224,source:'공사내역서',procurement:'관급',quantityType:'계약수량'}],packages:[{name:'의료가스 패키지',type:'전문공사·시공',score:97,target:'낙찰 시공사·기계설비사',timing:'지금',substitute:'제한적',items:['의료가스 동관 4,860m','밸브·아웃렛·시험 포함']},{name:'클린 공조 패키지',type:'공급+시공',score:94,target:'기계설비사',timing:'지금~착공',substitute:'중간',items:['AHU 14대','HEPA 대응','자동제어 연동']},{name:'방화구획 패키지',type:'공급+시공',score:88,target:'전문건설사',timing:'착공 전',substitute:'높음',items:['60분 방화문 148EA','방화구획 도면 연계']}],specs:[{label:'의료가스',type:'official'},{label:'HEPA',type:'official'},{label:'60분 방화',type:'official'},{label:'감염관리',type:'ai'}],aiMaterials:[{name:'항균 내장재',score:87,reason:'의료시설·감염관리 요구 분석',target:'전문건설사',timing:'착공 전',official:false},{name:'스마트 병실 센서',score:74,reason:'의료시설 운영 디지털화 사례 분석',target:'발주처',timing:'공사중',official:false}],costSheet:[{name:'재료비',amount:'221억',ratio:'49.3%'},{name:'노무비',amount:'91억',ratio:'20.3%'},{name:'경비',amount:'58억',ratio:'12.9%'},{name:'관리·이윤',amount:'41억',ratio:'9.1%'}],files:[{name:'공사내역서.xlsx',meta:'XLSX · 7.4MB',type:'공사내역서'},{name:'기계장비일람표.xlsx',meta:'XLSX · 2.9MB',type:'일람표'},{name:'의료가스특기시방서.pdf',meta:'PDF · 18MB',type:'시방서'},{name:'방화구획도.pdf',meta:'PDF · 32MB',type:'설계도서'}],aiSummary:'공공의료원 증축공사로 계약이 완료되어 전문공종과 주요 장비 발주가 시작될 가능성이 높은 단계입니다. 의료가스·클린 공조·방화구획처럼 전문성이 높은 패키지는 일반 자재보다 납품+시공 또는 전문공사 형태의 영업기회로 분류하는 것이 적절합니다.'
  }
];

const state = { mode:'all', view:'default', basis:'project', sort:'recommend', query:'', selected:null, map:false, filters:{} };
const saved = new Set(JSON.parse(localStorage.getItem('jootek-bid-saved') || '[]'));
const $ = (id) => document.getElementById(id);
const esc = (value='') => String(value).replace(/[&<>'\"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
const uniq = arr => [...new Set(arr.filter(Boolean))];
const dateValue = v => /^\d{4}-\d{2}-\d{2}$/.test(v||'') ? new Date(`${v}T00:00:00`).getTime() : Number.MAX_SAFE_INTEGER;

function init(){
  populateFilters(); bindEvents(); renderMetrics(); render();
  const params = new URLSearchParams(location.search); const projectId = Number(params.get('project'));
  if(projectId && projects.some(p=>p.id===projectId)) openDetail(projectId, false);
}

function populateFilters(){
  fillSelect('stageFilter', uniq(projects.map(p=>p.stage))); fillSelect('regionFilter', uniq(projects.map(p=>p.region))); fillSelect('tradeFilter', uniq(projects.map(p=>p.trade))); fillSelect('usageFilter', uniq(projects.map(p=>p.usage)));
  fillSelect('fStage', uniq(projects.map(p=>p.stage))); fillSelect('fRegion', uniq(projects.map(p=>p.region))); fillSelect('fUsage', uniq(projects.map(p=>p.usage))); fillSelect('fTrade', uniq(projects.map(p=>p.trade)));
  const specLabels = uniq(projects.flatMap(p=>p.specs.map(s=>s.label))).slice(0,12);
  $('specChecks').innerHTML = specLabels.map((s,i)=>`<label><input type="checkbox" data-spec-filter="${esc(s)}" id="spec_${i}"> ${esc(s)}</label>`).join('');
}
function fillSelect(id, items){ const el=$(id); items.sort((a,b)=>a.localeCompare(b,'ko')).forEach(v=>{ const o=document.createElement('option'); o.value=v; o.textContent=v; el.appendChild(o); }); }

function bindEvents(){
  $('modeTabs').addEventListener('click', e=>{ const b=e.target.closest('button[data-mode]'); if(!b)return; state.mode=b.dataset.mode; [...$('modeTabs').querySelectorAll('button')].forEach(x=>x.classList.toggle('active',x===b)); render(); });
  $('preset').addEventListener('click', e=>{ const b=e.target.closest('button[data-view]'); if(!b)return; state.view=b.dataset.view; [...$('preset').querySelectorAll('button')].forEach(x=>x.classList.toggle('active',x===b)); render(); });
  $('basisSwitch').addEventListener('click', e=>{ const b=e.target.closest('button[data-basis]'); if(!b)return; state.basis=b.dataset.basis; [...$('basisSwitch').querySelectorAll('button')].forEach(x=>x.classList.toggle('active',x===b)); showToast(state.basis==='project'?'프로젝트 단위로 묶어 표시합니다.':'공고 차수 기준 보기로 전환했습니다.'); render(); });
  ['stageFilter','regionFilter','tradeFilter','costFilter','deadlineFilter','usageFilter','signalFilter','fitFilter'].forEach(id=>$(id).addEventListener('change', render));
  $('sort').addEventListener('change',e=>{state.sort=e.target.value; render();});
  $('search').addEventListener('input', e=>{state.query=e.target.value.trim(); render();});
  $('search').addEventListener('keydown', e=>{ if(e.key==='Enter'){ state.query=e.target.value.trim(); render(); showToast(`“${state.query || '전체'}” 검색 결과를 반영했습니다.`); }});
  $('queryHints').addEventListener('click',e=>{const b=e.target.closest('button[data-query]');if(!b)return;$('search').value=b.dataset.query;state.query=b.dataset.query;render();});
  $('openFilters').onclick=()=>openFilters(true); $('closeFilters').onclick=()=>openFilters(false); $('applyFilters').onclick=()=>{ state.filters=readAdvancedFilters(); openFilters(false); render();}; $('resetFilters').onclick=resetAdvancedFilters; $('saveFilter').onclick=()=>showToast('현재 상세 검색조건을 저장했습니다.');
  $('saveSearch').onclick=()=>showToast('현재 검색조건을 저장하고 알림 대상으로 등록했습니다.');
  $('toggleMap').onclick=()=>{state.map=!state.map;$('mapPanel').hidden=!state.map;$('toggleMap').textContent=state.map?'목록만 보기':'지도 보기'; if(state.map)renderMap(currentProjects());};
  $('tableBody').addEventListener('click', e=>{ const star=e.target.closest('.star'); if(star){e.stopPropagation();toggleSaved(Number(star.dataset.id));return;} const tr=e.target.closest('tr[data-id]'); if(tr)openDetail(Number(tr.dataset.id)); });
  $('tableBody').addEventListener('mouseover',handleTooltip); $('tableBody').addEventListener('mouseout',()=>hideTooltip());
  $('tableHead').addEventListener('click',e=>{const th=e.target.closest('th[data-sort]'); if(!th)return;state.sort=th.dataset.sort;$('sort').value=state.sort;render();});
  $('closeDetail').onclick=closeDetail; $('backdrop').onclick=()=>{closeDetail();openFilters(false)};
  $('detailStar').onclick=()=>{if(state.selected)toggleSaved(state.selected,true)}; $('detailSave').onclick=()=>{if(state.selected)toggleSaved(state.selected,true)};
  $('detailAction').onclick=()=>{ const p=projects.find(x=>x.id===state.selected); if(!p)return; localStorage.setItem(`jootek-crm-${p.id}`,JSON.stringify({project:p.name,action:p.next,createdAt:new Date().toISOString()})); showToast(`“${p.name}”을(를) 업무기회로 저장했습니다.`); };
  $('shareProject').onclick=async()=>{const p=projects.find(x=>x.id===state.selected);if(!p)return;const url=`${location.origin}${location.pathname}?project=${p.id}`;try{await navigator.clipboard.writeText(url);showToast('프로젝트 링크를 복사했습니다.')}catch{showToast('공유 링크: '+url)}};
  $('detailBody').addEventListener('click',e=>{ const acc=e.target.closest('[data-accordion]'); if(acc){const target=$(acc.dataset.accordion);target.classList.toggle('open');acc.textContent=target.classList.contains('open')?'접기 ▴':'상세보기 ▾';} const nav=e.target.closest('[data-anchor]');if(nav){const sec=$(nav.dataset.anchor);sec?.scrollIntoView({behavior:'smooth'});} const fake=e.target.closest('[data-fake-action]'); if(fake)showToast(fake.dataset.fakeAction); });
  document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeDetail();openFilters(false)}});
}

function readAdvancedFilters(){
  const checkedSpecs=[...document.querySelectorAll('[data-spec-filter]:checked')].map(x=>x.dataset.specFilter);
  return { stage:$('fStage').value,region:$('fRegion').value,usage:$('fUsage').value,trade:$('fTrade').value,method:$('fMethod').value,minCost:Number($('fMinCost').value||0),minArea:Number($('fMinArea').value||0),contest:$('fContest').checked,map:$('fMap').checked,regionLimited:$('fRegionLimited').checked,performance:$('fPerformance').checked,joint:$('fJoint').checked,pq:$('fPQ').checked,patent:$('fPatent').checked,material:$('fMaterial').value.trim().toLowerCase(),spec:$('fSpec').value.trim().toLowerCase(),procurement:$('fProcurement').value,supply:$('fSupply').value,bill:$('fBill').checked,qty:$('fQty').checked,specDoc:$('fSpecDoc').checked,schedule:$('fSchedule').checked,aiMaterial:$('fAiMaterial').value.trim().toLowerCase(),aiScore:Number($('fAiScore').value||0),target:$('fTarget').value,aiOnly:$('fAiOnly').checked,now:$('fNow').checked,specLabels:checkedSpecs,awarded:$('fAwarded').checked,award30:$('fAward30').checked,beforeStart:$('fBeforeStart').checked,salesNow:$('fSalesNow').checked,correction:$('fCorrection').checked,rebid:$('fRebid').checked};
}
function resetAdvancedFilters(){ [...$('filterDrawer').querySelectorAll('input')].forEach(i=>{if(i.type==='checkbox')i.checked=false;else i.value=''}); [...$('filterDrawer').querySelectorAll('select')].forEach(s=>s.selectedIndex=0); state.filters={}; render(); showToast('상세필터를 초기화했습니다.'); }
function openFilters(open){ $('filterDrawer').classList.toggle('open',open); $('filterDrawer').setAttribute('aria-hidden',String(!open)); $('backdrop').classList.toggle('open',open || $('detailDrawer').classList.contains('open')); }

function currentProjects(){
  let list=projects.slice();
  if(state.mode==='bid')list=list.filter(p=>['공고중','설계완료'].includes(p.stage));
  if(state.mode==='award')list=list.filter(p=>['낙찰완료','계약','착공예정'].includes(p.stage));
  if(state.mode==='sales')list=list.filter(p=>p.packages.length||p.aiMaterials.length);
  if(state.mode==='saved')list=list.filter(p=>saved.has(p.id));
  const stage=$('stageFilter').value, region=$('regionFilter').value, trade=$('tradeFilter').value, usage=$('usageFilter').value, signal=$('signalFilter').value, fit=Number($('fitFilter').value||0);
  if(stage)list=list.filter(p=>p.stage===stage); if(region)list=list.filter(p=>p.region===region); if(trade)list=list.filter(p=>p.trade===trade); if(usage)list=list.filter(p=>p.usage===usage); if(fit)list=list.filter(p=>p.fit>=fit);
  const cost=$('costFilter').value;if(cost){const[a,b]=cost.split('-').map(Number);list=list.filter(p=>p.cost>=a&&p.cost<b)}
  const deadline=$('deadlineFilter').value;if(deadline==='urgent')list=list.filter(p=>/^D-[1-7]$/.test(p.dday));if(deadline==='open')list=list.filter(p=>p.stage==='공고중');if(deadline==='closed')list=list.filter(p=>['낙찰완료','계약','착공예정'].includes(p.stage));
  if(signal==='materials')list=list.filter(p=>p.materials.length);if(signal==='packages')list=list.filter(p=>p.packages.length);if(signal==='spec')list=list.filter(p=>p.specs.length);if(signal==='ai')list=list.filter(p=>p.aiMaterials.length);
  if(state.query){ const q=state.query.toLowerCase(); list=list.filter(p=>searchBlob(p).includes(q) || semanticQueryMatch(p,q)); }
  list=list.filter(advancedMatch);
  return sortProjects(list);
}
function searchBlob(p){return [p.name,p.noticeNo,p.address,p.stage,p.usage,p.org,p.region,p.trade,p.method,p.awarded,p.next,p.nextTarget,...p.badges,...p.conditionTags,...p.attachments,...p.materials.flatMap(m=>[m.name,m.spec,m.category,m.procurement]),...p.packages.flatMap(x=>[x.name,x.type,x.target,x.timing,...x.items]),...p.specs.map(s=>s.label),...p.aiMaterials.flatMap(x=>[x.name,x.reason,x.target,x.timing])].join(' ').toLowerCase()}
function semanticQueryMatch(p,q){
  if(q.includes('낙찰')&&p.awarded)return true;if(q.includes('착공')&&p.beforeStart)return true;if(q.includes('관급')&&p.materials.some(m=>m.procurement==='관급'))return true;if(q.includes('설계사 영업')&&p.nextTarget==='설계사')return true;if(q.includes('시공사 영업')&&p.nextTarget==='시공사')return true;if(q.includes('영업')&&(p.packages.length||p.aiMaterials.length))return true;return false;
}
function advancedMatch(p){const f=state.filters||{};if(f.stage&&p.stage!==f.stage)return false;if(f.region&&p.region!==f.region)return false;if(f.usage&&p.usage!==f.usage)return false;if(f.trade&&p.trade!==f.trade)return false;if(f.method&&p.method!==f.method)return false;if(f.minCost&&p.cost<f.minCost)return false;if(f.minArea&&p.area<f.minArea)return false;if(f.contest&&!p.hasContest)return false;if(f.map&&!p.hasMap)return false;if(f.regionLimited&&!p.regionLimited)return false;if(f.performance&&!p.performance)return false;if(f.joint&&!p.joint)return false;if(f.pq&&!p.pq)return false;if(f.patent&&!p.specs.some(s=>/특허|신기술/.test(s.label)))return false;if(f.correction&&!p.correction)return false;if(f.rebid&&!p.rebid)return false;if(f.material&&!p.materials.some(m=>`${m.name} ${m.category}`.toLowerCase().includes(f.material)))return false;if(f.spec&&!p.materials.some(m=>m.spec.toLowerCase().includes(f.spec)))return false;if(f.procurement&&!p.materials.some(m=>m.procurement===f.procurement)&&p.procurement!==f.procurement)return false;if(f.supply&&!p.packages.some(x=>x.type===f.supply))return false;if(f.bill&&!p.attachments.some(x=>x.includes('공사내역서')))return false;if(f.qty&&!p.attachments.some(x=>x.includes('물량내역서')))return false;if(f.specDoc&&!p.attachments.some(x=>x.includes('시방서')))return false;if(f.schedule&&!p.attachments.some(x=>x.includes('일람표')))return false;if(f.aiMaterial&&!p.aiMaterials.some(x=>x.name.toLowerCase().includes(f.aiMaterial)))return false;if(f.aiScore&&!p.aiMaterials.some(x=>x.score>=f.aiScore))return false;if(f.target&&!p.packages.some(x=>x.target.includes(f.target))&&!p.aiMaterials.some(x=>x.target===f.target))return false;if(f.aiOnly&&!p.aiMaterials.some(x=>!x.official))return false;if(f.now&&!p.aiMaterials.some(x=>/지금|현재/.test(x.timing)))return false;if(f.specLabels?.length&&!f.specLabels.every(s=>p.specs.some(x=>x.label===s)))return false;if(f.awarded&&!p.awarded)return false;if(f.award30&&!(p.awardAge!==null&&p.awardAge<=30))return false;if(f.beforeStart&&!p.beforeStart)return false;if(f.salesNow&&!/영업/.test(p.next))return false;return true;}
function sortProjects(list){const arr=list.slice();if(state.sort==='deadline')arr.sort((a,b)=>dateValue(a.deadline)-dateValue(b.deadline));else if(state.sort==='costDesc')arr.sort((a,b)=>b.cost-a.cost);else if(state.sort==='costAsc')arr.sort((a,b)=>a.cost-b.cost);else if(state.sort==='opp')arr.sort((a,b)=>b.opp-a.opp);else if(state.sort==='fit')arr.sort((a,b)=>b.fit-a.fit);else if(state.sort==='sales')arr.sort((a,b)=>Math.max(0,...b.packages.map(x=>x.score),...b.aiMaterials.map(x=>x.score))-Math.max(0,...a.packages.map(x=>x.score),...a.aiMaterials.map(x=>x.score)));else arr.sort((a,b)=>(b.opp*.35+b.fit*.25+Math.max(0,...b.packages.map(x=>x.score))*.25+b.ai*.8)-(a.opp*.35+a.fit*.25+Math.max(0,...a.packages.map(x=>x.score))*.25+a.ai*.8));return arr;}

const views={
  default:[['☆',''],['프로젝트',''],['진행단계',''],['예정 공사비','costDesc'],['입찰마감','deadline'],['발주처',''],['지역',''],['참가조건',''],['프로젝트 인텔리전스','opp'],['자재·스펙','sales'],['다음 기회','']],
  bid:[['☆',''],['프로젝트',''],['예정 공사비','costDesc'],['입찰마감','deadline'],['필요면허',''],['지역제한',''],['실적제한',''],['공동도급',''],['입찰방식',''],['우리 회사 적합도','fit']],
  sales:[['☆',''],['프로젝트',''],['프로젝트 단계',''],['공사비','costDesc'],['첨부분석',''],['실제수요',''],['관급/사급',''],['특이 스펙',''],['납품기회','sales'],['설계사/낙찰사',''],['영업 타이밍','']]
};
function render(){renderCounts();renderHead();const list=currentProjects();$('tableBody').innerHTML=list.map(rowForView).join('');$('emptyState').hidden=!!list.length;$('activeFilterSummary').innerHTML=`<b>${list.length}개</b> 프로젝트 · ${state.mode==='all'?'전체':modeLabel(state.mode)} · ${state.view==='default'?'기본 보기':state.view==='bid'?'입찰 참여 보기':'자재·영업 보기'}`;if(state.map)renderMap(list);updateSavedStars();}
function renderHead(){$('tableHead').innerHTML='<tr>'+views[state.view].map(([h,s],i)=>`<th ${s?`data-sort="${s}" class="sortable ${i===1?'projectCell':''}"`:`class="${i===1?'projectCell':''}"`}>${h}${s?' ↕':''}</th>`).join('')+'</tr>'}
function rowForView(p){return state.view==='bid'?bidRow(p):state.view==='sales'?salesRow(p):defaultRow(p)}
function projectHTML(p){return `<div class="projectName"><span>${esc(p.name)}</span><span class="badges">${p.badges.slice(0,3).map(b=>`<span class="badge ${b.includes('AI')?'ai':b==='낙찰'?'blue':b==='재공고'?'orange':''}">${esc(b)}</span>`).join('')}${p.badges.length>3?`<span class="badge">+${p.badges.length-3}</span>`:''}</span></div><div class="sub">${esc(p.address)} · ${esc(p.usage)} · ${esc(p.constructionType)}</div>`}
function stageClass(p){return p.stageCls||'open'}
function defaultRow(p){return `<tr data-id="${p.id}"><td><button class="star ${saved.has(p.id)?'saved':''}" data-id="${p.id}" aria-label="관심 저장">${saved.has(p.id)?'★':'☆'}</button></td><td>${projectHTML(p)}</td><td class="center"><span class="stage ${stageClass(p)}">${esc(p.stage)}</span></td><td class="center"><div class="money">${p.cost}억</div><div class="sub">${p.unit}만원/㎡</div></td><td class="center"><b>${esc(p.deadline)}</b><div class="sub"><span class="dday ${/^D-[1-3]$/.test(p.dday)?'urgent':''}">${esc(p.dday)}</span></div></td><td class="center">${esc(p.org)}</td><td class="center">${esc(p.region)}</td><td><b>${esc(p.trade)}</b><div class="chips">${p.conditionTags.slice(0,3).map(x=>`<span class="chip">${esc(x)}</span>`).join('')}</div></td><td class="center scoreCell intel" data-tip="intel" data-id="${p.id}"><strong>기회 ${p.opp}</strong><div class="scoreLabel">우리회사 ${p.fit}%</div></td><td class="demand" data-tip="demand" data-id="${p.id}"><div class="demandTop"><span class="officialDemand">실제 ${p.actual}</span><span class="aiDemand">AI ${p.ai}</span></div><div class="sub">${esc(p.demand)}</div></td><td><div class="nextNow">지금</div><div class="nextAction">${esc(p.next)}</div><div class="sub">${esc(p.nextSub)}</div></td></tr>`}
function bidRow(p){return `<tr data-id="${p.id}"><td><button class="star ${saved.has(p.id)?'saved':''}" data-id="${p.id}">${saved.has(p.id)?'★':'☆'}</button></td><td>${projectHTML(p)}</td><td class="center"><div class="money">${p.cost}억</div></td><td class="center"><b>${esc(p.deadline)}</b><div class="sub">${esc(p.dday)}</div></td><td>${esc(p.trade)}</td><td class="center">${p.regionLimited?esc(p.region):'제한없음'}</td><td class="center">${p.performance?'있음':'없음'}</td><td class="center">${p.joint?'가능':'불가/미정'}</td><td class="center">${esc(p.method)}</td><td class="center intel" data-tip="intel" data-id="${p.id}"><div class="money">${p.fit}%</div><div class="sub">${p.fit>=80?'참여 추천':p.fit>=70?'검토 추천':'조건 확인'}</div></td></tr>`}
function salesRow(p){const procureCounts={관급:p.materials.filter(m=>m.procurement==='관급').length,사급:p.materials.filter(m=>m.procurement==='사급').length};return `<tr data-id="${p.id}"><td><button class="star ${saved.has(p.id)?'saved':''}" data-id="${p.id}">${saved.has(p.id)?'★':'☆'}</button></td><td>${projectHTML(p)}</td><td class="center"><span class="stage ${stageClass(p)}">${esc(p.stage)}</span></td><td class="center"><div class="money">${p.cost}억</div></td><td><b>${p.attachments.length}종 분석</b><div class="docIcons">${p.attachments.slice(0,3).map(x=>`<span class="docIcon">${esc(x.replace('공사',''))}</span>`).join('')}</div></td><td class="demand" data-tip="demand" data-id="${p.id}"><b>실제 ${p.actual}종</b><div class="sub">${esc(p.demand)}</div></td><td class="center">관 ${procureCounts.관급} · 사 ${procureCounts.사급}<div class="sub">${esc(p.procurement)}</div></td><td><div class="sub">${p.specs.slice(0,2).map(s=>`<span class="${s.type==='ai'?'signalAi':'signalGood'}">${esc(s.label)}</span>`).join(' · ')||'확인중'}</div></td><td class="center demand" data-tip="demand" data-id="${p.id}"><b class="signalGood">${p.packages.length}건</b><div class="sub">최고 ${Math.max(0,...p.packages.map(x=>x.score),...p.aiMaterials.map(x=>x.score))}%</div></td><td>${esc(p.awarded||p.designer.name)}</td><td><div class="nextNow">지금</div><div class="nextAction">${esc(p.next)}</div><div class="sub">${esc(p.nextSub)}</div></td></tr>`}

function renderCounts(){const all=projects.length,bid=projects.filter(p=>['공고중','설계완료'].includes(p.stage)).length,award=projects.filter(p=>['낙찰완료','계약','착공예정'].includes(p.stage)).length,sales=projects.filter(p=>p.packages.length||p.aiMaterials.length).length;$('countAll').textContent=all;$('countBid').textContent=bid;$('countAward').textContent=award;$('countSales').textContent=sales;$('countSaved').textContent=saved.size;}
function renderMetrics(){const real=projects.reduce((n,p)=>n+p.actual,0),packs=projects.reduce((n,p)=>n+p.packages.length,0),files=projects.reduce((n,p)=>n+p.files.length,0),urgent=projects.filter(p=>/^D-[1-7]$/.test(p.dday)).length;$('metricStrip').innerHTML=`<div class="metric"><div><strong>${projects.length}</strong><span>분석 프로젝트</span></div><span class="delta">데모 데이터</span></div><div class="metric"><div><strong>${files}</strong><span>분석 첨부파일</span></div><span class="delta">내역·시방·일람</span></div><div class="metric"><div><strong>${real}</strong><span>구조화 실제수요</span></div><span class="delta">공식 문서 기반</span></div><div class="metric"><div><strong>${packs}</strong><span>납품·시공 패키지</span></div><span class="delta">영업기회</span></div><div class="metric"><div><strong>${urgent}</strong><span>7일 이내 마감</span></div><span class="delta">즉시 검토</span></div>`}
function modeLabel(m){return ({bid:'입찰 참여',award:'낙찰·계약',sales:'자재 영업기회',saved:'관심 프로젝트'})[m]||'전체'}

function handleTooltip(e){const cell=e.target.closest('[data-tip]');if(!cell)return;const p=projects.find(x=>x.id===Number(cell.dataset.id));if(!p)return;const rect=cell.getBoundingClientRect();if(cell.dataset.tip==='intel')showTooltip(`<h4>프로젝트 인텔리전스</h4>${tt('기회점수',`${p.opp}점`)}${tt('우리회사 적합도',`${p.fit}%`)}${tt('면허',p.trade)}${tt('입찰방식',p.method)}<hr><div class="muted">기회점수와 회사 적합도는 서로 다른 지표입니다.</div>`,rect);else showTooltip(`<h4>실제 확인 수요 <span class="sourceTag">공식</span></h4>${p.materials.slice(0,4).map(m=>tt(m.name,`${m.qty.toLocaleString()} ${m.unit}`)).join('')||'<div class="muted">확인된 실제 물량 없음</div>'}<hr><h4>납품·AI 기회 <span class="sourceTag ai">분석</span></h4>${p.packages.slice(0,2).map(x=>tt(x.name,`${x.score}점`)).join('')}${p.aiMaterials.slice(0,2).map(x=>tt(x.name,`${x.score}%`)).join('')}`,rect)}
function tt(a,b){return `<div class="ttrow"><span>${esc(a)}</span><b>${esc(b)}</b></div>`}
function showTooltip(html,rect){$('tooltip').innerHTML=html;$('tooltip').classList.add('open');const w=320;let left=Math.min(innerWidth-w-12,Math.max(12,rect.left));let top=Math.min(innerHeight-260,rect.bottom+8);$('tooltip').style.left=`${left}px`;$('tooltip').style.top=`${Math.max(12,top)}px`}
function hideTooltip(){$('tooltip').classList.remove('open')}

function renderMap(list){const positions=[[18,22],[72,28],[58,62],[32,69],[47,37],[79,74]];$('mapCanvas').innerHTML=list.map((p,i)=>`<button class="mapPin ${stageClass(p)}" data-map-id="${p.id}" style="left:${positions[(p.id-1)%positions.length][0]}%;top:${positions[(p.id-1)%positions.length][1]}%"><i></i><span>${esc(p.name)}</span></button>`).join('');[...$('mapCanvas').querySelectorAll('[data-map-id]')].forEach(b=>b.onclick=()=>openDetail(Number(b.dataset.mapId)));}

function openDetail(id,push=true){const p=projects.find(x=>x.id===id);if(!p)return;state.selected=id;$('detailBody').innerHTML=detailHTML(p);$('detailDrawer').classList.add('open');$('detailDrawer').setAttribute('aria-hidden','false');$('backdrop').classList.add('open');updateDetailActions(p);if(push){const u=new URL(location.href);u.searchParams.set('project',id);history.replaceState({},'',u)} }
function closeDetail(){if(!$('detailDrawer').classList.contains('open'))return;$('detailDrawer').classList.remove('open');$('detailDrawer').setAttribute('aria-hidden','true');$('backdrop').classList.toggle('open',$('filterDrawer').classList.contains('open'));state.selected=null;const u=new URL(location.href);u.searchParams.delete('project');history.replaceState({},'',u.pathname+u.search)}
function updateDetailActions(p){const isSaved=saved.has(p.id);$('detailStar').textContent=isSaved?'★ 관심':'☆ 관심';$('detailSave').textContent=isSaved?'★ 관심':'☆ 관심';$('detailAction').textContent=/입찰/.test(p.next)?'입찰 검토 시작':/영업/.test(p.next)?'영업기회 저장':'업무로 저장';}
function toggleSaved(id,fromDetail=false){if(saved.has(id))saved.delete(id);else saved.add(id);localStorage.setItem('jootek-bid-saved',JSON.stringify([...saved]));render();const p=projects.find(x=>x.id===id);showToast(`${p.name} ${saved.has(id)?'관심 프로젝트로 저장':'관심에서 해제'}했습니다.`);if(fromDetail){state.selected=id;updateDetailActions(p)}}
function updateSavedStars(){renderCounts()}

function detailHTML(p){
  const topMaterials=p.materials.slice(0,4).map(m=>`${m.name} ${m.qty.toLocaleString()}${m.unit}`).join(' · ') || '공식 문서에서 확인된 실제 자재 없음';
  const topCost=p.costSheet.slice(0,4).map(c=>`${c.name} ${c.amount}`).join(' · ') || '공사원가계산서 미확보';
  return `<div class="docPreview"><div class="docPage"><h5>공사 입찰 공고</h5><div class="docLine"></div><div class="docLine w70"></div><div class="docLine"></div><div class="docStamp"><b>${esc(p.name)}</b><br>공고번호 ${esc(p.noticeNo)}<br>발주기관 ${esc(p.org)}<br>추정가격 ${p.cost}억원</div><div class="docLine"></div><div class="docLine w45"></div></div><div class="thumbs"><div class="thumb">1</div><div class="thumb">2</div><div class="thumb">3</div><div class="thumb">+${Math.max(1,p.files.length)}</div></div></div>
  <div class="detail">
    <div class="headerBadges"><span class="badge ${p.stageCls==='award'?'blue':p.stageCls==='soon'?'orange':'green'}">${esc(p.stage)}</span><span class="badge">${esc(p.method)}</span><span class="badge">${esc(p.constructionType)}</span><span class="badge">${esc(p.usage)}</span></div>
    <h2>${esc(p.name)}</h2><div class="sub">${esc(p.noticeNo)} · ${esc(p.org)}</div>
    <div class="kpis"><div class="kpi"><strong>${p.cost}억</strong><small>예정 공사비</small></div><div class="kpi"><strong>${esc(p.dday)}</strong><small>현재 일정</small></div><div class="kpi"><strong>${p.opp}</strong><small>기회점수</small></div></div>
    <div class="detailActions"><button class="primary" data-fake-action="나라장터 공식 공고 원문으로 이동합니다. (데모)">나라장터 공고 원문 ↗</button><button data-anchor="sec-files">첨부파일 ${p.files.length}</button><button data-fake-action="알림 설정을 저장했습니다.">알림설정</button></div>
    <nav class="stickyDetailNav"><button data-anchor="sec-timeline">타임라인</button><button data-anchor="sec-ai">AI 분석</button><button data-anchor="sec-materials">실제수요</button><button data-anchor="sec-cost">원가</button><button data-anchor="sec-sales">영업</button><button data-anchor="sec-files">파일</button></nav>
    <section class="section" id="sec-timeline"><div class="sectionTitle"><h3>프로젝트 타임라인</h3><span class="sourceTag">주택 데이터</span></div><div class="timeline">${p.timeline.map(([n,d,s])=>`<div class="step ${s==='current'?'current':s==='future'?'future':''}"><i class="dotStep"></i>${esc(n)}<small>${esc(d)}</small></div>`).join('')}</div></section>
    <section class="section"><div class="sectionTitle"><h3>프로젝트 개요</h3><span class="sourceTag">공식</span></div><div class="kv"><div>발주기관</div><b>${esc(p.org)}</b><div>공사구분</div><b>${esc(p.constructionType)}</b><div>건축용도</div><b>${esc(p.usage)}</b><div>연면적</div><b>${p.area.toLocaleString()}㎡</b><div>예정공사비</div><b>${p.cost}억원</b><div>입찰방식</div><b>${esc(p.method)} · ${esc(p.awardMethod)}</b><div>필요면허</div><b>${esc(p.trade)}</b></div></section>
    <section class="section"><div class="sectionTitle"><h3>공사 위치</h3><button class="accordion" data-fake-action="주소를 복사했습니다.">주소 복사</button></div><div class="summaryLine">${esc(p.address)}</div>${miniMap(p)}</section>
    <section class="section" id="sec-ai"><div class="sectionTitle"><h3>AI 프로젝트 분석</h3><span class="sourceTag ai">AI 분석</span></div><div class="aiBox">${esc(p.aiSummary)}<div class="meta"><span>근거: 공고·첨부파일·설계공모·유사 프로젝트</span><span>신뢰도 높음</span></div></div></section>
    <section class="section"><div class="sectionTitle"><h3>프로젝트 인텔리전스</h3><button class="accordion" data-accordion="scoreEvidence">산정근거 보기 ▾</button></div><div class="signalGrid"><div class="signalCard"><b>기회점수 ${p.opp}</b><span class="muted">프로젝트 자체 매력도</span><div class="progress"><i style="width:${p.opp}%"></i></div></div><div class="signalCard"><b>우리회사 ${p.fit}%</b><span class="muted">참여조건 적합도</span><div class="progress"><i style="width:${p.fit}%"></i></div></div></div><div class="accordionBody" id="scoreEvidence"><div class="kv" style="margin-top:9px"><div>사업 추진 확실성</div><b>${Math.min(99,p.opp+6)}</b><div>데이터 신뢰도</div><b>${p.attachments.length>=3?'높음':'중간'}</b><div>면허 적합</div><b>${p.fit>=70?'충족/검토':'조건 확인'}</b><div>영업 가능성</div><b>${Math.max(...p.packages.map(x=>x.score),...p.aiMaterials.map(x=>x.score),0)}</b></div></div></section>
    <section class="section" id="sec-materials"><div class="sectionTitle"><h3>실제 자재·장비 및 물량</h3><span class="sourceTag">공식 문서</span></div><div class="summaryLine"><b>${p.actual}종</b> · ${esc(topMaterials)}</div><button class="accordion" data-accordion="materials_${p.id}">상세보기 ▾</button><div class="accordionBody" id="materials_${p.id}">${materialTable(p)}</div></section>
    <section class="section"><div class="sectionTitle"><h3>납품·시공 패키지</h3><span class="sourceTag">구조화 수요</span></div>${p.packages.length?p.packages.map(packageHTML).join(''):'<div class="muted">공식 물량 데이터가 확보되면 생성됩니다.</div>'}</section>
    <section class="section" id="sec-cost"><div class="sectionTitle"><h3>공사원가계산</h3><span class="sourceTag">공사원가</span></div><div class="summaryLine">${esc(topCost)}</div><button class="accordion" data-accordion="cost_${p.id}">원가 상세보기 ▾</button><div class="accordionBody" id="cost_${p.id}">${costTable(p)}</div></section>
    <section class="section" id="sec-sales"><div class="sectionTitle"><h3>영업 인사이트</h3><span class="sourceTag ai">AI 분석</span></div><div class="package"><div class="packageHead"><div><h4>지금 · ${esc(p.next)}</h4><span class="muted">추천대상 ${esc(p.nextTarget)}</span></div><strong class="opp">추천</strong></div><div class="summaryLine" style="margin-top:6px">${esc(p.nextSub)}</div><button class="accordion" data-fake-action="이 프로젝트를 영업기회로 저장했습니다.">영업기회 저장</button></div><div class="signalGrid" style="margin-top:8px"><div class="signalCard"><b>${esc(p.issuer.name)}</b><span class="muted">최근 3년 ${p.issuer.count}건 · 평균 ${esc(p.issuer.avg)}</span></div><div class="signalCard"><b>${esc(p.designer.name)}</b><span class="muted">유사 프로젝트 ${p.designer.similar}건</span></div></div><div class="specs" style="margin-top:8px">${p.issuer.pattern.map(x=>`<span class="spec">${esc(x)}</span>`).join('')}</div></section>
    <section class="section"><div class="sectionTitle"><h3>AI 자재 영업기회</h3><span class="sourceTag ai">AI 예상 · 실제 자재와 분리</span></div><div class="aiBox">공식 물량이 아니라 프로젝트 특성·설계·유사사례를 분석한 추가 영업 가능성입니다.</div>${p.aiMaterials.map(aiMaterialHTML).join('')||'<div class="muted">추론 가능한 추가 기회가 없습니다.</div>'}</section>
    <section class="section"><div class="sectionTitle"><h3>특이 스펙·대체가능성</h3></div><div class="specs">${p.specs.map(s=>`<span class="spec ${s.type==='ai'?'ai':''}">${s.type==='ai'?'AI 탐지 · ':'공식 · '}${esc(s.label)}</span>`).join('')}</div></section>
    <section class="section"><div class="sectionTitle"><h3>입찰·계약 정보</h3><span class="sourceTag">공식</span></div><div class="kv"><div>공고번호</div><b>${esc(p.noticeNo)}</b><div>계약방법</div><b>${esc(p.method)}</b><div>낙찰방법</div><b>${esc(p.awardMethod)}</b><div>지역제한</div><b>${p.regionLimited?esc(p.region):'없음'}</b><div>실적제한</div><b>${p.performance?'있음':'없음'}</b><div>공동도급</div><b>${p.joint?'가능':'불가/미정'}</b>${p.awarded?`<div>낙찰사</div><b>${esc(p.awarded)}</b><div>낙찰금액</div><b>${esc(p.awardPrice)} · ${esc(p.awardRate)}</b>`:''}</div></section>
    <section class="section" id="sec-files"><div class="sectionTitle"><h3>첨부파일</h3><span>${p.files.length}개</span></div>${p.files.map(f=>`<div class="fileRow"><div><b>${esc(f.name)}</b><div class="fileMeta">${esc(f.meta)} · ${esc(f.type)}</div></div><div><button data-fake-action="${esc(f.name)} 미리보기를 엽니다. (데모)">미리보기</button><button data-fake-action="${esc(f.name)} 다운로드를 시작합니다. (데모)">다운로드 ↓</button></div></div>`).join('')}<button class="accordion" data-fake-action="첨부파일 전체 다운로드를 시작합니다. (데모)">전체 다운로드</button></section>
    <section class="section"><div class="sectionTitle"><h3>데이터 출처</h3></div><div class="kv"><div>공식 출처</div><b>조달청 나라장터</b><div>공고번호</div><b>${esc(p.noticeNo)}</b><div>분석 상태</div><b>${p.attachments.length}종 문서 구조화 완료</b><div>데이터 원칙</div><b>공식 Fact / AI 추론 분리</b></div></section>
  </div>`;
}
function materialTable(p){if(!p.materials.length)return '<div class="muted">공식 문서에서 확인된 실제 자재·장비가 없습니다.</div>';return `<div class="miniScroll"><table class="miniTable"><thead><tr><th>품목</th><th>규격</th><th>수량</th><th>조달</th></tr></thead><tbody>${p.materials.map(m=>`<tr><td><b>${esc(m.name)}</b><div class="fileMeta">${esc(m.source)} · ${esc(m.quantityType)}</div></td><td>${esc(m.spec)}</td><td>${m.qty.toLocaleString()} ${esc(m.unit)}</td><td>${esc(m.procurement)}</td></tr>`).join('')}</tbody></table></div>`}
function costTable(p){if(!p.costSheet.length)return '<div class="muted">공사원가계산서가 아직 확보되지 않았습니다.</div>';return `<div class="miniScroll"><table class="miniTable"><thead><tr><th>항목</th><th>금액</th><th>구성비</th></tr></thead><tbody>${p.costSheet.map(c=>`<tr><td>${esc(c.name)}</td><td><b>${esc(c.amount)}</b></td><td>${esc(c.ratio)}</td></tr>`).join('')}</tbody></table></div>`}
function packageHTML(x){return `<div class="package"><div class="packageHead"><div><h4>${esc(x.name)}</h4><span class="muted">${esc(x.type)} · ${esc(x.target)} · ${esc(x.timing)}</span></div><span class="opp">${x.score}점</span></div><ul>${x.items.map(i=>`<li>${esc(i)}</li>`).join('')}</ul><div class="meta"><span>대체가능성 ${esc(x.substitute)}</span><span>근거: 공식 내역 구조화</span></div></div>`}
function aiMaterialHTML(x){return `<div class="package" style="background:var(--aiBg);border-color:#ddd7ff"><div class="packageHead"><div><h4>${esc(x.name)}</h4><span class="muted">${esc(x.target)} · ${esc(x.timing)}</span></div><span class="signalAi">${x.score}%</span></div><div class="summaryLine" style="margin-top:6px">${esc(x.reason)}</div><div class="meta"><span>AI 추론</span><span>${x.official?'공식 내역 포함':'공식 내역 미확인'}</span></div></div>`}
function miniMap(p){return `<div class="map"><svg viewBox="0 0 460 145" preserveAspectRatio="none" aria-label="미니지도"><rect width="460" height="145" fill="#eef2ef"/><path d="M-20 95 L480 48" stroke="#fff" stroke-width="20"/><path d="M260 -20 L300 170" stroke="#fff" stroke-width="13"/><g fill="#dce5df"><rect x="28" y="22" width="70" height="34"/><rect x="116" y="16" width="58" height="44"/><rect x="330" y="74" width="80" height="40"/><rect x="82" y="98" width="88" height="28"/></g><circle cx="275" cy="72" r="7" fill="#e25454"/><circle cx="275" cy="72" r="14" fill="none" stroke="#e25454" opacity=".25" stroke-width="5"/></svg><button data-fake-action="주택지도의 동일 주소로 이동합니다. (데모)">주택지도에서 보기 ↗</button></div>`}
function showToast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>t.classList.remove('show'),2200)}

document.addEventListener('DOMContentLoaded',init);
