const projects=[
{ id:1,name:'제주대학교 미래교육관 신축공사',address:'제주 제주시 제주대학로 102',stage:'공고중',stageCls:'open',cost:205,unit:261,deadline:'26.08.19',dday:'D-6',org:'제주대학교',region:'제주',condition:'건축공사업',badges:['설계공모','내역서','제로에너지'],opp:87,fit:92,actual:37,ai:6,next:'입찰 검토',nextSub:'설계사·참여 시공사 검토 가능',awarded:'',awardPrice:'',demand:'철근·레미콘·창호 외',attach:['공사내역서','시방서','설계도서','창호일람표'],materials:[['철근 SD400','HD10·13·16·19','ton',69.33,'공사내역서'],['레미콘','25-30-150 외 3종','㎥',770,'공사내역서'],['H형강 SS275','5개 규격','ton',29.01,'공사내역서'],['그라스울패널','T75 준불연','㎡',520,'시방서']],packages:[{name:'철근·콘크리트 패키지',type:'제품·자재 납품',score:91,items:['철근 SD400 69.33ton','레미콘 770㎥','H형강 SS275 29.01ton']},{name:'외피·창호 패키지',type:'공급+시공',score:84,items:['그라스울패널 T75 520㎡','시스템창호·유리 사양 검토 대상']}],specs:['공식 · 제로에너지','공식 · 준불연','AI 탐지 · 고성능 외피'],aiMat:[['고성능 로이유리','86%','설계·유사 프로젝트 분석'],['흡음재','78%','교육·커뮤니티 공간'],['외장패널','71%','당선안 외관 분석']],files:[['공사입찰공고서.pdf','PDF · 2.4MB'],['공사내역서.xlsx','XLSX · 4.8MB'],['건축공사 시방서.pdf','PDF · 15.2MB'],['설계도서.zip','ZIP · 128MB']]},
{ id:2,name:'대구 공영주차장 조성공사',address:'대구 달서구 ○○로 31',stage:'낙찰완료',stageCls:'award',cost:74,unit:188,deadline:'26.08.05',dday:'낙찰',org:'대구광역시',region:'대구',condition:'토목공사업',badges:['물량','낙찰','AI 분석'],opp:90,fit:74,actual:42,ai:8,next:'시공사 영업',nextSub:'낙찰 후 9일',awarded:'대구종합건설',awardPrice:'67.8억',demand:'가로등·주차블록·아스콘 외',attach:['공사내역서','물량내역서','시방서'],materials:[['PE주차블록','750×150×120mm','EA',792,'공사내역서'],['태양광가로등','DMTPS-310,50W,5m','본',20,'공사내역서'],['아스콘,표층','WC-2 가열3등급','ton',2152,'공사내역서'],['PE이중벽하수관','Φ400','m',27,'공사내역서'],['무소음그레이팅','500×1000×50','조',24,'공사내역서']],packages:[{name:'태양광 가로등 패키지',type:'장비·기계 납품',score:94,items:['태양광가로등 20본','가로등기초 20EA','앵커볼트 80개','베이스커버 20개']},{name:'주차시설 패키지',type:'제품 납품',score:92,items:['PE주차블록 792개','주차라인·고정핀 관련 시공']},{name:'도로포장 패키지',type:'자재+장비',score:88,items:['아스콘 2,152ton','포설·다짐 13,255㎡','디스트리뷰터 3,800ℓ급']},{name:'배수시설 패키지',type:'제품+시공',score:81,items:['PE이중벽하수관 Φ400 27m','PE밴드 3조','무소음그레이팅 24조']}],specs:['공식 · 태양광','공식 · 특정모델','AI 탐지 · 대체가능성 확인 필요'],aiMat:[['고효율 조명 제어','82%','태양광가로등 연계'],['주차유도 설비','76%','주차장 용도 분석']],files:[['공사내역서.xlsx','XLSX · 3.7MB'],['물량내역서.xlsx','XLSX · 1.8MB'],['특기시방서.pdf','PDF · 8.1MB']]},
{ id:3,name:'부산 공공도서관 신축공사',address:'부산 해운대구 ○○로 88',stage:'착공예정',stageCls:'soon',cost:312,unit:289,deadline:'26.07.29',dday:'착공 D-22',org:'부산광역시',region:'부산',condition:'건축공사업',badges:['당선안','원가','낙찰'],opp:93,fit:88,actual:48,ai:9,next:'자재 영업',nextSub:'착공 D-22',awarded:'부산건설',awardPrice:'287억',demand:'창호·단열·외장 외',attach:['공사내역서','시방서','마감재료표','창호일람표'],materials:[['시스템창호','단열바 적용','㎡',860,'창호일람표'],['복층유리','24mm','㎡',1240,'창호일람표'],['흡음패널','T25','㎡',690,'마감재료표'],['외장패널','준불연','㎡',1830,'마감재료표']],packages:[{name:'창호·유리 패키지',type:'공급+시공',score:96,items:['시스템창호 860㎡','복층유리 1,240㎡','방화창 별도 사양']},{name:'외장·흡음 마감 패키지',type:'자재+시공',score:89,items:['외장패널 1,830㎡','흡음패널 690㎡']}],specs:['공식 · 준불연','공식 · 고단열','공식 · 방화창'],aiMat:[['로이복층유리 고성능 대안','91%','창호일람표·에너지 요구 분석'],['친환경 흡음재','84%','도서관 실내환경 요구']],files:[['창호일람표.pdf','PDF · 6.2MB'],['마감재료표.xlsx','XLSX · 2.2MB'],['공사원가계산서.xlsx','XLSX · 1.1MB']]},
{ id:4,name:'광주 어린이복합문화시설 건립사업',address:'광주 북구 ○○길 15',stage:'설계완료',stageCls:'open',cost:149,unit:242,deadline:'입찰예정',dday:'예정',org:'광주광역시',region:'광주',condition:'입찰공고 전',badges:['설계공모','당선안','AI 분석'],opp:86,fit:68,actual:0,ai:7,next:'설계사 영업',nextSub:'사양 반영 가능 시점',awarded:'',awardPrice:'',demand:'공식 물량 미확인',attach:['설계공모','당선안','실시설계 요약'],materials:[],packages:[],specs:['AI 탐지 · 흡음성능','AI 탐지 · 친환경 마감'],aiMat:[['시스템창호','82%','대형 교육·문화시설 외피 분석'],['흡음재','79%','어린이·문화공간 분석'],['친환경 마감재','77%','공공시설 용도 분석']],files:[['당선안.pdf','PDF · 21MB'],['설계설명서.pdf','PDF · 12MB']]}
];
let currentView='default';
const head=document.getElementById('tableHead'),body=document.getElementById('tableBody'),tooltip=document.getElementById('tooltip');
const views={default:['☆','프로젝트','진행단계 ↕','예정 공사비 ↕','입찰마감 ↕','발주처','지역','참가조건','프로젝트 인텔리전스 ↕','자재·스펙 ↕','다음 기회'],bid:['☆','프로젝트','예정 공사비 ↕','입찰마감 ↕','필요면허','지역제한','실적제한','공동도급','입찰방식','우리 회사 적합도 ↕'],sales:['☆','프로젝트','프로젝트 단계','공사비 ↕','첨부분석','실제수요','관급/사급','특이 스펙','AI 자재기회 ↕','설계사/낙찰사','영업 타이밍 ↕']};
function renderHead(){head.innerHTML='<tr>'+views[currentView].map((h,i)=>`<th class="${i===1?'projectCell':''}">${h}</th>`).join('')+'</tr>'}
function statusClass(p){return p.stageCls==='award'?'award':p.stageCls==='soon'?'soon':'open'}
function projectHTML(p){return `<div class="projectName">${p.name}<span class="badges">${p.badges.slice(0,3).map(b=>`<span class="badge ${b.includes('AI')?'ai':b==='낙찰'?'blue':''}">${b}</span>`).join('')}${p.badges.length>3?`<span class="badge">+${p.badges.length-3}</span>`:''}</span></div><div class="sub">${p.address}</div>`}
function defaultRow(p){return `<tr data-id="${p.id}"><td><button class="star">☆</button></td><td>${projectHTML(p)}</td><td class="center"><span class="stage ${statusClass(p)}">${p.stage}</span></td><td class="center moneyCell"><div class="money">${p.cost}억</div><div class="sub">${p.unit}만원/㎡</div></td><td class="center"><b>${p.deadline}</b><div class="sub"><span class="dday">${p.dday}</span></div></td><td class="center">${p.org}</td><td class="center">${p.region}</td><td><b>${p.condition}</b><div class="chips"><span class="chip">지역</span><span class="chip">실적</span></div></td><td class="center scoreCell intel" data-id="${p.id}"><strong>기회 ${p.opp}</strong><div class="scoreLabel">우리회사 ${p.fit}%</div></td><td class="demand" data-id="${p.id}"><div class="demandTop"><span class="officialDemand">실제 ${p.actual}</span><span class="aiDemand">AI기회 ${p.ai}</span></div><div class="sub">${p.demand}</div></td><td><div class="nextNow">지금</div><div class="nextAction">${p.next}</div><div class="sub">${p.nextSub}</div></td></tr>`}
function bidRow(p){return `<tr data-id="${p.id}"><td><button class="star">☆</button></td><td>${projectHTML(p)}</td><td class="center"><div class="money">${p.cost}억</div></td><td class="center"><b>${p.deadline}</b><div class="sub">${p.dday}</div></td><td>${p.condition}</td><td class="center">${p.region}</td><td class="center">최근 5년</td><td class="center">가능</td><td class="center">일반경쟁</td><td class="center intel" data-id="${p.id}"><div class="money">${p.fit}%</div><div class="sub">${p.fit>=80?'참여 추천':'검토 필요'}</div></td></tr>`}
function salesRow(p){return `<tr data-id="${p.id}"><td><button class="star">☆</button></td><td>${projectHTML(p)}</td><td class="center"><span class="stage ${statusClass(p)}">${p.stage}</span></td><td class="center"><div class="money">${p.cost}억</div></td><td><b>${p.attach.length}종 분석</b><div class="sub">${p.attach.slice(0,3).join(' · ')}</div></td><td class="demand" data-id="${p.id}"><b>실제 ${p.actual}종</b><div class="sub">납품패키지 ${p.packages.length}건</div></td><td class="center">관급·사급<br><span class="sub">원문 기준</span></td><td><div class="sub">${p.specs.slice(0,2).join(' · ')||'확인중'}</div></td><td class="center demand" data-id="${p.id}"><b style="color:var(--ai)">${p.ai}종</b><div class="sub">최고 ${p.aiMat[0]?.[1]||'-'}</div></td><td>${p.awarded||'설계사 확인'}</td><td><div class="nextNow">지금</div><div class="nextAction">${p.next}</div><div class="sub">${p.nextSub}</div></td></tr>`}
function filtered(){const q=document.getElementById('search').value.trim().toLowerCase();if(!q)return projects;return projects.filter(p=>[p.name,p.address,p.org,p.region,p.condition,p.demand,...p.materials.flat(),...p.specs,...p.aiMat.flat()].join(' ').toLowerCase().includes(q))}
function renderRows(list=filtered()){body.innerHTML=list.map(currentView==='bid'?bidRow:currentView==='sales'?salesRow:defaultRow).join('');wireRows()}
function wireRows(){body.querySelectorAll('tr').forEach(tr=>tr.addEventListener('click',e=>{if(e.target.closest('.star'))return;openDetail(+tr.dataset.id)}));body.querySelectorAll('.star').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();b.classList.toggle('saved');b.textContent=b.classList.contains('saved')?'★':'☆'}));body.querySelectorAll('.intel').forEach(el=>{el.addEventListener('mouseenter',e=>showIntel(projects.find(p=>p.id===+el.dataset.id),e));el.addEventListener('mouseleave',hideTooltip)});body.querySelectorAll('.demand').forEach(el=>{el.addEventListener('mouseenter',e=>showDemand(projects.find(p=>p.id===+el.dataset.id),e));el.addEventListener('mouseleave',hideTooltip)})}
function positionTooltip(e){tooltip.style.left=Math.min(window.innerWidth-330,e.clientX+14)+'px';tooltip.style.top=Math.min(window.innerHeight-280,e.clientY+14)+'px';tooltip.classList.add('open')}
function showIntel(p,e){tooltip.innerHTML=`<h4>프로젝트 기회점수 ${p.opp}</h4><div class="ttrow"><span>사업 추진 확실성</span><b>95</b></div><div class="ttrow"><span>예산 안정성</span><b>92</b></div><div class="ttrow"><span>영업 가능성</span><b>${p.opp}</b></div><hr><h4>우리 회사 적합도 ${p.fit}%</h4><div class="ttrow"><span>면허</span><b>✓ 충족</b></div><div class="ttrow"><span>지역</span><b>${p.fit>=80?'✓ 충족':'△ 검토'}</b></div><div class="ttrow"><span>실적</span><b>${p.fit>=75?'✓ 충족':'△ 부족'}</b></div>`;positionTooltip(e)}
function showDemand(p,e){tooltip.innerHTML=`<h4>실제 확인 수요</h4>${p.materials.slice(0,4).map(m=>`<div class="ttrow"><span>${m[0]}</span><b>${m[3]} ${m[2]}</b></div>`).join('')||'<div class="muted">공식 물량 미확인</div>'}<div class="muted" style="font-size:9px">공사내역서·물량내역서 등 공식 문서 기준</div><hr><h4 style="color:var(--ai)">AI 자재 영업기회</h4>${p.aiMat.slice(0,3).map(m=>`<div class="ttrow"><span>${m[0]}</span><b>${m[1]}</b></div>`).join('')}`;positionTooltip(e)}
function hideTooltip(){tooltip.classList.remove('open')}
function timeline(p){return `<div class="timeline"><div class="step"><span class="dot"></span>사업기획<small>24.08</small></div><div class="step"><span class="dot"></span>설계공모<small>25.02</small></div><div class="step"><span class="dot"></span>설계사선정<small>25.05</small></div><div class="step"><span class="dot"></span>설계완료<small>26.06</small></div><div class="step current"><span class="dot"></span>${p.stage}<small>현재</small></div><div class="step future"><span class="dot"></span>착공<small>예상</small></div></div>`}
function detailHTML(p){return `<div class="docPreview"><div class="docPage"><b>${p.name}</b><br><br>공 사 입 찰 공 고<br><br>1. 공사개요<br>2. 입찰 및 계약방법<br>3. 참가자격<br>4. 예정가격 및 낙찰자 결정<br><br><br>※ 실제 공고 PDF 미리보기 영역</div><div class="thumbs"><div class="thumb">1</div><div class="thumb">2</div><div class="thumb">3</div><div class="thumb">+12</div></div></div><div class="detail"><h2>${p.name}</h2><div>${p.badges.map(b=>`<span class="badge ${b.includes('AI')?'ai':''}">${b}</span>`).join(' ')}</div><div class="kpis"><div class="kpi"><strong>${p.cost}억원</strong><small>예정 공사비 · ${p.unit}만원/㎡</small></div><div class="kpi"><strong>${p.dday}</strong><small>${p.deadline}</small></div></div><div class="detailActions"><button class="primary">나라장터 공고 원문 ↗</button><button>첨부파일</button><button>알림</button></div>
<section class="section"><div class="sectionTitle"><h3>프로젝트 타임라인</h3><span class="sourceTag">주택 데이터</span></div>${timeline(p)}</section>
<section class="section"><div class="sectionTitle"><h3>프로젝트 개요</h3><span class="sourceTag">공식</span></div><div class="kv"><div>발주기관</div><div>${p.org}</div><div>공사구분</div><div>신축·조성</div><div>예정 공사비</div><div>${p.cost}억원</div><div>입찰조건</div><div>${p.condition}</div><div>공사위치</div><div>${p.address}</div></div><div class="map"><svg viewBox="0 0 450 145"><rect width="450" height="145" fill="#edf1f2"/><path d="M0 95 C80 70 120 120 200 90 S330 45 450 70" fill="none" stroke="#cfd8dc" stroke-width="9"/><path d="M60 0 L120 145 M250 0 L230 145 M370 0 L320 145" stroke="#d8dfe2" stroke-width="5"/><circle cx="225" cy="72" r="8" fill="#d75151"/><path d="M225 80 l-7 13 h14z" fill="#d75151"/></svg><button>주택지도에서 보기 ↗</button></div></section>
<section class="section"><div class="sectionTitle"><h3>AI 프로젝트 분석</h3><span class="sourceTag ai">AI 분석</span></div><div class="aiBox">공고문과 첨부된 공사내역서·시방서·설계자료를 함께 분석했습니다. 현재 프로젝트에서는 <b>${p.next}</b>가 우선 행동으로 판단됩니다.<div class="meta"><span>근거 보기</span><span>·</span><span>신뢰도 높음</span></div></div></section>
<section class="section"><div class="sectionTitle"><h3>프로젝트 인텔리전스</h3><span class="sourceTag ai">분석</span></div><div class="kpis"><div class="kpi"><strong>${p.opp}점</strong><small>프로젝트 기회점수</small></div><div class="kpi"><strong>${p.fit}%</strong><small>우리 회사 적합도</small></div></div></section>
<section class="section"><div class="sectionTitle"><h3>첨부파일 분석</h3><span class="sourceTag">${p.attach.length}종 분석</span></div><div class="chips">${p.attach.map(x=>`<span class="chip">${x} ✓</span>`).join('')}</div><p class="summaryLine">원문 추출항목을 그대로 나열하지 않고 <b>작업물량 / 제품수량 / 계약수량</b>을 구분해 실제 수요로 구조화합니다.</p></section>
<section class="section"><div class="sectionTitle"><h3>실제 자재 및 물량</h3><span class="sourceTag">공식 문서</span></div><div class="summaryLine">${p.materials.length?p.materials.slice(0,3).map(m=>`${m[0]} ${m[3]}${m[2]}`).join(' · ')+' 외 '+Math.max(0,p.actual-3)+'종':'공식 문서에서 확인된 자재 물량 없음'}</div><button class="accordion" data-target="mat-${p.id}">상세 자재 보기 ▾</button><div class="accordionBody" id="mat-${p.id}"><div class="miniScroll"><table class="miniTable"><thead><tr><th>품목</th><th>규격</th><th>단위</th><th>수량</th><th>출처</th></tr></thead><tbody>${p.materials.map(m=>`<tr><td><b>${m[0]}</b></td><td>${m[1]}</td><td>${m[2]}</td><td>${m[3]}</td><td>${m[4]}</td></tr>`).join('')||'<tr><td colspan="5">확인된 공식 물량 없음</td></tr>'}</tbody></table></div></div></section>
<section class="section"><div class="sectionTitle"><h3>납품·시공 영업기회</h3><span class="sourceTag">첨부파일 구조화</span></div><p class="summaryLine">여러 원문 행을 실제 견적 가능한 조달 패키지로 묶습니다.</p>${p.packages.map(x=>`<div class="package"><div class="packageHead"><div><h4>${x.name}</h4><span class="muted">${x.type}</span></div><div class="opp">기회 ${x.score}</div></div><ul>${x.items.map(i=>`<li>${i}</li>`).join('')}</ul></div>`).join('')||'<div class="muted">분석 가능한 조달 패키지 없음</div>'}</section>
<section class="section"><div class="sectionTitle"><h3>특이 사양·스펙</h3><span class="sourceTag">시방서·일람표</span></div><div class="specs">${p.specs.map(s=>`<span class="spec ${s.includes('AI')?'ai':''}">${s}</span>`).join('')}</div><p class="summaryLine">특정 모델, 특허·신기술, 동등 이상 허용, 성능·인증 조건을 원문 근거와 연결합니다.</p></section>
<section class="section"><div class="sectionTitle"><h3>AI 자재 영업기회</h3><span class="sourceTag ai">AI 추론</span></div><div class="aiBox"><b>실제 자재와 완전히 별도 정보입니다.</b><br>공식 내역에 직접 확인되지 않은 추가 영업 가능성을 프로젝트 특성·설계·유사 프로젝트 기반으로 추론합니다.</div>${p.aiMat.map(m=>`<div class="package"><div class="packageHead"><div><h4>${m[0]}</h4><span class="muted">${m[2]}</span></div><div class="opp" style="color:var(--ai)">${m[1]}</div></div></div>`).join('')}</section>
<section class="section"><div class="sectionTitle"><h3>영업 타이밍</h3><span class="sourceTag ai">AI 분석</span></div><div class="kv"><div>현재 추천</div><div><b>${p.next}</b></div><div>우선 접촉</div><div>${p.awarded||'설계사·입찰 참여사'}</div><div>추천 이유</div><div>${p.stage.includes('낙찰')||p.stage.includes('착공')?'낙찰 이후 자재·협력업체 선정 가능성이 높은 구간':'사양·견적 검토가 가능한 프로젝트 단계'}</div></div></section>
<section class="section"><div class="sectionTitle"><h3>첨부파일</h3><span class="sourceTag">원문</span></div>${p.files.map(f=>`<div class="fileRow"><div><b>${f[0]}</b><div class="fileMeta">${f[1]}</div></div><div><button>미리보기</button><button>다운로드 ↓</button></div></div>`).join('')}</section>
<section class="section"><div class="sectionTitle"><h3>공식 출처</h3><span class="sourceTag">조달청</span></div><div class="kv"><div>데이터 출처</div><div>조달청 나라장터</div><div>최종 수집</div><div>2026.08.21 16:42</div><div>첨부분석</div><div>2026.08.21 16:48</div></div></section></div>`}
function openDetail(id){const p=projects.find(x=>x.id===id);document.getElementById('detailBody').innerHTML=detailHTML(p);document.getElementById('detailDrawer').classList.add('open');document.getElementById('backdrop').classList.add('open');document.querySelectorAll('.accordion').forEach(btn=>btn.addEventListener('click',()=>{const el=document.getElementById(btn.dataset.target);el.classList.toggle('open');btn.textContent=el.classList.contains('open')?'접기 ▴':'상세 자재 보기 ▾'}));document.querySelector('#detailFooter .primary').textContent=(p.stage==='공고중'||p.stage==='설계완료')?'입찰 검토 시작':'영업기회 저장'}
function closeDetail(){document.getElementById('detailDrawer').classList.remove('open');document.getElementById('backdrop').classList.remove('open')}
function setView(v){currentView=v;document.querySelectorAll('#preset button').forEach(b=>b.classList.toggle('active',b.dataset.view===v));renderHead();renderRows()}
document.querySelectorAll('#preset button').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));document.querySelectorAll('#modeTabs button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('#modeTabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');if(b.dataset.mode==='sales')setView('sales');else if(b.dataset.mode==='bid')setView('bid');else setView('default')}));document.getElementById('search').addEventListener('input',()=>renderRows());document.getElementById('openFilters').addEventListener('click',()=>document.getElementById('filterDrawer').classList.add('open'));document.getElementById('closeFilters').addEventListener('click',()=>document.getElementById('filterDrawer').classList.remove('open'));document.getElementById('closeDetail').addEventListener('click',closeDetail);document.getElementById('backdrop').addEventListener('click',closeDetail);renderHead();renderRows();